### ISSUE TITLE
First simple rocket take 20 years to build

### ISSUE THREAD

**Issue by tdubic** [KSP-RO/ProgramsIssueTracker#87] opened 2022-09-12 18:27 UTC
I am using Launch Complexes and Programs mode.
I have one save that is working fine and I manage to go in orbit, but I am trying to make new game and I can`t. When I build first simple rocket and launch complex it takes +20 years to build. I have put engineers in complex, made tooling and so on.... I spend hours with diferent programs, administrators and others combinations and I can`t figure out what is making this.

**Comment by Tsits11** [comment] 2022-09-12 20:08
I'm having the exact same problem.... for some reason the build points don't seem to add up and the rocket takes 20 years to build on a new save... plus some random bugs e.g. i cant switch effectively between complexes , i click on the switch button but the game still stays and displays the hangar stats and build points... I think they're connected somehow

**Comment by NathanKell** [comment] 2022-09-13 04:47
Could not reproduce.
Steps followed:
1. Admin->select Suborbital Research as my program
2. Mission Control->Accept First Flight and Karman Line contracts
3. Go to VAB, put together a WAC Corporal (just the rocket, no Tiny Tim booster).
4. Click "New LC" and change the defaults to 10m height, 2m each width and length, then click build.
5. Exit VAB, warp to complete.
6. Enter VAB, the new launch complex will be selected. Tool everything (RP-1 icon->tooling->Tool all) and click the 'launch' button to start the WAC integrating.
7. Exit VAB and click Staff. Hire 10 applicants as engineers and add them to the newly-completed launch complex (Click Engineers. Hold Shift and click Hire. Then with the LC selected as destination, hold shift and click the + by Assign to assign all 10 there.)
8. Warp to complete.
9. Click Rollout to roll the new rocket out. Warp to complete.

Ready to launch.


![image](https://user-images.githubusercontent.com/5144098/189810955-db2bccba-7562-4299-8cd6-c806c713b346.png)

**Closed as completed by NathanKell** 2022-09-13 04:47 UTC

**Comment by NathanKell** [comment] 2022-09-13 04:48
Note that you don't need to edit LC defaults, I mention it only because my LC took longer to build than a purely minimal one would.

**Comment by tdubic** [comment] 2022-09-13 18:29
I am not sure but I think it is some problem with administrators. So now I first build first rocket then select administrators. When I select administrators first then build time is some weird number 5-E3 or unlimited. There are other numbers that are wrong, like in the beginning you can have 400 engineers in a hangar.

**Comment by NathanKell** [comment] 2022-09-13 23:10
As I said above I literally did exactly that, went to admin first.
I need precise repro steps recounting *everything* you did, because I cannot reproduce any problems myself. My guess is that you are somehow not allocating your engineers to the new launch complex. And yes, you certainly can have 400 engineers in the hangar, that is intended. The hangar operates by different rules.

**Comment by tdubic** [comment] 2022-09-18 09:31
Is there solution to start without space planes?. I manage to start few new saves, but when I try new save without space plane and follow instructions still time to build first tiny rocket is until 1996.

**Comment by NathanKell** [comment] 2022-09-19 03:02
As I have now said multiple times, I need **precise reproduction steps** or I cannot help you.
